[package]
name = "geofabrik-catenary-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
osmpbf = "0.3.4"
reqwest = "0.12.5"
tokio = { version = "1.39.2", features = ["full"] }

[[bin]]
name = "download_osms_and_reduce_to_rail_lines"
path = "src/dl_and_reduce.rs"
